// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class _Default {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.TextBox txtFirstName;
	
	protected System.Web.UI.WebControls.TextBox txtLastName;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
	
	protected System.Web.UI.WebControls.TextBox txtPhone;
	
	protected System.Web.UI.WebControls.TextBox txtEmail;
	
	protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
	
	protected System.Web.UI.WebControls.TextBox txtCity;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
	
	protected System.Web.UI.WebControls.TextBox txtState;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
	
	protected System.Web.UI.WebControls.TextBox txtZip;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
	
	protected System.Web.UI.WebControls.TextBox txtPassword;
	
	protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
	
	protected System.Web.UI.WebControls.Button Button1;
	
	protected System.Web.UI.WebControls.Label lblError;
	
	protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
}
