// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Default2 {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Label lblFirstName;
	
	protected System.Web.UI.WebControls.Label lblLastName;
	
	protected System.Web.UI.WebControls.Label lblPhone;
	
	protected System.Web.UI.WebControls.Label lblEmail;
	
	protected System.Web.UI.WebControls.Label lblCity;
	
	protected System.Web.UI.WebControls.Label lblState;
	
	protected System.Web.UI.WebControls.Label lblZip;
	
	protected System.Web.UI.WebControls.Label lblPassword;
	
	protected System.Web.UI.WebControls.Button btnYes;
	
	protected System.Web.UI.WebControls.Button btnNo;
}
